#pragma once

#include "actionevent.hpp"
#include "actionlistener.hpp"
#include "cliprectangle.hpp"
#include "color.hpp"
#include "deathlistener.hpp"
#include "event.hpp"
#include "exception.hpp"
#include "focushandler.hpp"
#include "focuslistener.hpp"
#include "font.hpp"
#include "genericinput.hpp"
#include "graphics.hpp"
#include "gui.hpp"
#include "image.hpp"
#include "imagefont.hpp"
#include "imageloader.hpp"
#include "input.hpp"
#include "inputevent.hpp"
#include "key.hpp"
#include "keyevent.hpp"
#include "keyinput.hpp"
#include "keylistener.hpp"
#include "listmodel.hpp"
#include "mouseevent.hpp"
#include "mouseinput.hpp"
#include "mouselistener.hpp"
#include "rectangle.hpp"
#include "selectionevent.hpp"
#include "selectionlistener.hpp"
#include "widget.hpp"
#include "widgetlistener.hpp"
#include "widgets/button.hpp"
#include "widgets/checkbox.hpp"
#include "widgets/container.hpp"
#include "widgets/dropdown.hpp"
#include "widgets/icon.hpp"
#include "widgets/imagebutton.hpp"
#include "widgets/label.hpp"
#include "widgets/listbox.hpp"
#include "widgets/scrollarea.hpp"
#include "widgets/slider.hpp"
#include "widgets/radiobutton.hpp"
#include "widgets/tab.hpp"
#include "widgets/tabbedarea.hpp"
#include "widgets/textbox.hpp"
#include "widgets/textfield.hpp"
#include "widgets/window.hpp"
#include "platform.hpp"

class Widget;

extern "C"
{
    GCN_CORE_DECLSPEC extern const char* gcnGuichanVersion();
}
